version: "3.9"

services:
  node:
    image: node:17-alpine
    container_name: "shokusuru"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm install
        npm install -g nodemon
        npm run dev
      "

  gulp:
    image: node:17-alpine
    container_name: "gulp"
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "
        npm install
        npm run build
      "
